# .pre-commit-config.yaml
repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks: [{id: black}]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.6
    hooks: [{id: ruff}]
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.17
    hooks: [{id: mdformat}]
